version: '3'
volumes:
  postgres_data: {}
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 80:3000
  db:
    image: postgres:10.10
    volumes:
      - postgres_data:/var/lib/postgresql/data
